apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-monitor
  namespace: ashapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-monitor
  template:
    metadata:
      labels:
        app: flask-monitor
    spec:
      containers:
      - name: flask-monitor
        image: ashwanth01/flask-monitor:latest
        env:
          - name: MYSQL_URI
            value: "mysql+pymysql://ashuser:ashpass@mysql.ashapp.svc.cluster.local:3306/ashdb"
        ports:
          - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-monitor
  namespace: ashapp
spec:
  selector:
    app: flask-monitor
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: NodePort

