apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: ashapp
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mysql   # folder on your node

