# app.py (Main AshApp)
import boto3
import subprocess
import json
import os
import shutil
from datetime import datetime
from flask import Flask, request, jsonify, send_from_directory, session, redirect
import requests

# --------------------------
# FLASK APP
# --------------------------
app = Flask(__name__, static_folder="frontend", static_url_path="")
app.secret_key = os.environ.get("SECRET_KEY", "supersecretkey")

# --------------------------
# ENSURE AWS CLI INSTALLED
# --------------------------
def ensure_aws_cli():
    aws_path = shutil.which("aws")
    if aws_path is None:
        print("AWS CLI not found. Installing...")
        try:
            subprocess.run([
                "curl", "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip", "-o", "awscliv2.zip"
            ], check=True)
            subprocess.run(["unzip", "-o", "awscliv2.zip"], check=True)
            subprocess.run(["/tmp/aws/install"], check=True)
            aws_path = shutil.which("aws")
            print(f"AWS CLI installed successfully at {aws_path}")
        except subprocess.CalledProcessError as e:
            print("Failed to install AWS CLI:", e)
            aws_path = None
    else:
        print(f"AWS CLI already installed at {aws_path}")
    return aws_path

AWS_CLI_PATH = ensure_aws_cli()

# --------------------------
# SPRING BOOT URL
# --------------------------
SPRING_BOOT_URL = os.environ.get("SPRING_BOOT_URL", "http://history-service:8081")

# --------------------------
# MONITORING URL
# --------------------------
MONITOR_URL = os.environ.get("MONITOR_URL", "http://localhost:6000/monitor/log")

def log_to_monitor(user_id, service, endpoint, action_type, request_data, response_summary):
    try:
        # Mask sensitive info
        if isinstance(request_data, dict):
            for key in ["access_key", "secret_key", "token", "password"]:
                if key in request_data:
                    request_data[key] = "****"
        requests.post(MONITOR_URL, json={
            "user_id": user_id,
            "service": service,
            "endpoint": endpoint,
            "action_type": action_type,
            "request_data": request_data,
            "response_summary": response_summary,
            "ip_address": request.remote_addr if request else "",
            "user_agent": request.headers.get("User-Agent", "") if request else ""
        }, timeout=1)
    except:
        pass

# --------------------------
# HISTORY FUNCTIONS
# --------------------------
def save_to_history(query, output):
    payload = {"query": query, "output": output}
    try:
        response = requests.post(f"{SPRING_BOOT_URL}/history/save", json=payload)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        print("Error saving history:", e)
        return None

def get_history():
    try:
        response = requests.get(f"{SPRING_BOOT_URL}/history/list")
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        print("Error fetching history:", e)
        return []

# --------------------------
# AWS BEDROCK CLIENT
# --------------------------
def get_bedrock_client():
    if "aws_access_key" not in session or "aws_secret_key" not in session:
        return None
    return boto3.client(
        "bedrock-runtime",
        region_name=session.get("aws_region", "us-east-1"),
        aws_access_key_id=session["aws_access_key"],
        aws_secret_access_key=session["aws_secret_key"],
    )

def ask_bedrock(prompt):
    bedrock_runtime = get_bedrock_client()
    if not bedrock_runtime:
        return "Not logged in to AWS."
    try:
        body = {
            "anthropic_version": "bedrock-2023-05-31",
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": 500,
            "temperature": 0.7,
        }
        response = bedrock_runtime.invoke_model(
            modelId="anthropic.claude-3-sonnet-20240229-v1:0",
            contentType="application/json",
            accept="application/json",
            body=json.dumps(body),
        )
        result = json.loads(response["body"].read())
        return result["content"][0]["text"].strip()
    except Exception as e:
        print("Bedrock invocation failed:", e)
        return f"Bedrock invocation failed: {e}"

# --------------------------
# RUN AWS CLI COMMAND
# --------------------------
def run_command_from_claude(prompt):
    print("Processing query:", prompt)

    command_prompt = (
        f'You are an expert in AWS CLI. Return a valid AWS CLI command for: "{prompt}". '
        f'Do not include explanations or placeholders. Default region: {session.get("aws_region", "us-east-1")}'
    )
    command = ask_bedrock(command_prompt)
    print("Command generated by Bedrock:", command)

    if not AWS_CLI_PATH:
        return command, "AWS CLI path not found in container."

    if command.strip().startswith("aws "):
        command = command.replace("aws", AWS_CLI_PATH, 1)

    aws_access = session.get("aws_access_key")
    aws_secret = session.get("aws_secret_key")
    aws_region = session.get("aws_region", "us-east-1")

    if not aws_access or not aws_secret:
        return command, "AWS credentials missing. Please login first."

    env = os.environ.copy()
    env["AWS_ACCESS_KEY_ID"] = aws_access
    env["AWS_SECRET_ACCESS_KEY"] = aws_secret
    env["AWS_DEFAULT_REGION"] = aws_region
    env["PATH"] = f"{os.path.dirname(AWS_CLI_PATH)}:" + env.get("PATH", "")

    try:
        output = subprocess.check_output(command, shell=True, stderr=subprocess.STDOUT, env=env)
        return command, output.decode()
    except subprocess.CalledProcessError as e:
        err = e.output.decode()
        print("Command execution failed:", err)
        if "InvalidClientTokenId" in err or "AuthFailure" in err:
            return command, "AWS session invalid. Please login again."
        return command, err

# --------------------------
# REACT LOGIN ROUTES
# --------------------------
login_build_path = os.path.join(os.path.dirname(__file__), "login", "build")

@app.route("/login", defaults={"path": ""})
@app.route("/login/<path:path>")
def serve_login(path):
    full_path = os.path.join(login_build_path, path)
    if path != "" and os.path.exists(full_path):
        return send_from_directory(login_build_path, path)
    return send_from_directory(login_build_path, "index.html")

# --------------------------
# MAIN ROUTE (AshApp)
# --------------------------
@app.route("/")
def index():
    if not session.get("aws_access_key") or not session.get("aws_secret_key"):
        session.clear()
        return redirect("/login")
    return send_from_directory(app.static_folder, "index.html")  # frontend/ -> AshApp

# --------------------------
# API ROUTES (Login, User, Ask, Confirm, History)
# --------------------------
@app.route("/api/login", methods=["POST"])
def api_login():
    data = request.get_json()
    access_key = data.get("access_key")
    secret_key = data.get("secret_key")
    region = data.get("region")

    try:
        sts_client = boto3.client(
            "sts",
            aws_access_key_id=access_key,
            aws_secret_access_key=secret_key,
            region_name=region,
        )
        identity = sts_client.get_caller_identity()
        session["aws_access_key"] = access_key
        session["aws_secret_key"] = secret_key
        session["aws_region"] = region
        session["aws_username"] = identity.get("Arn", "Unknown").split("/")[-1]
        session["aws_account_id"] = identity.get("Account", "")
        print("Login successful:", session["aws_username"])

        # Log login
        log_to_monitor(
            user_id=session["aws_username"],
            service="AshApp",
            endpoint="/api/login",
            action_type="login",
            request_data={"region": region},
            response_summary={"success": True}
        )

        return jsonify({"success": True, "username": session["aws_username"]})
    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 400

@app.route("/api/logout", methods=["POST"])
def api_logout():
    log_to_monitor(
        user_id=session.get("aws_username", "anonymous"),
        service="AshApp",
        endpoint="/api/logout",
        action_type="logout",
        request_data={},
        response_summary={"success": True}
    )
    session.clear()
    return jsonify({"success": True})

@app.route("/api/user", methods=["GET"])
def api_user():
    if not session.get("aws_access_key") or not session.get("aws_secret_key"):
        session.clear()
        return jsonify({"logged_in": False, "error": "AWS session missing. Please login again."})
    return jsonify({
        "logged_in": True,
        "username": session.get("aws_username", ""),
        "region": session.get("aws_region", "")
    })

@app.route("/api/ask", methods=["POST"])
def api_handler():
    data = request.get_json()
    query = data.get("query")
    if not query:
        return jsonify({"error": "No query provided"}), 400

    action = query.lower()
    if any(word in action for word in ["create", "delete", "modify", "update"]):
        return jsonify({"confirmation_needed": True, "query": query})

    command, output = run_command_from_claude(query)
    formatted_output = f"Command: {command}\n{output.strip()}"
    save_to_history(query, formatted_output)

    log_to_monitor(
        user_id=session.get("aws_username", "anonymous"),
        service="AshApp",
        endpoint="/api/ask",
        action_type="ask",
        request_data={"query": query},
        response_summary={"output": formatted_output[:500]}
    )

    return jsonify({"confirmation_needed": False, "output": formatted_output})

@app.route("/api/confirm", methods=["POST"])
def api_confirm():
    data = request.get_json()
    query = data.get("query")
    decision = data.get("decision")
    if decision.lower() != "accept":
        log_to_monitor(
            user_id=session.get("aws_username", "anonymous"),
            service="AshApp",
            endpoint="/api/confirm",
            action_type="confirm-decline",
            request_data={"query": query, "decision": decision},
            response_summary={"output": "Action declined."}
        )
        return jsonify({"output": "Action declined."})

    command, output = run_command_from_claude(query)
    formatted_output = f"Command: {command}\n{output.strip()}"
    save_to_history(query, formatted_output)

    log_to_monitor(
        user_id=session.get("aws_username", "anonymous"),
        service="AshApp",
        endpoint="/api/confirm",
        action_type="confirm-accept",
        request_data={"query": query, "decision": decision},
        response_summary={"output": formatted_output[:500]}
    )

    return jsonify({"output": formatted_output})

@app.route("/api/history", methods=["GET"])
def api_history():
    history = get_history()
    return jsonify(history)

# --------------------------
# MAIN
# --------------------------
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    print(f"Main AshApp running on port {port}")
    app.run(host="0.0.0.0", port=port)

